apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
spec:
  selector:
    matchLabels:
      app: go-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: dycsail/go-echo:latest
        ports:
        - containerPort: 38001
