apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
spec:
  selector:
    matchLabels:
      app: go-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: dycsail/go-echo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 38001
---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-service
spec:
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 38001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/auth-type: 'cognito'
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"userPoolARN":"arn:aws:cognito-idp:us-east-2:442507722261:userpool/us-east-2_kyxvlm7s8","userPoolClientID":"o8ned9b7gdmcu9qhth0bmelkp","userPoolDomain":"auth.baseplatform2.irondev.io"}'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-2:442507722261:certificate/b98ca09a-e55b-4cfc-a565-92a736a26320'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /goecho
            pathType: Prefix
            backend:
              service:
                name: go-echo-service
                port:
                  number: 80
