apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
spec:
  selector:
    matchLabels:
      app: go-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: dycsail/go-echo:latest
        ports:
        - containerPort: 38001
---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-service
spec:
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 38001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/auth-type: 'cognito'
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"userPoolARN":"arn:aws:cognito-idp:us-east-1:442507722261:userpool/us-east-1_58Z01Uv1o","userPoolClientID":"1l14fu00lghu6jijo79lb3uf5e","userPoolDomain":"mn-test"}'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /goecho
            pathType: Prefix
            backend:
              service:
                name: go-echo-service
                port:
                  number: 80
