apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
spec:
  selector:
    matchLabels:
      app: go-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: go-echo
    spec:
      containers:
      - name: go-echo
        image: dycsail/go-echo:latest
        ports:
        - containerPort: 38001
---
apiVersion: v1
kind: Service
metadata:
  name: go-echo-service
spec:
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 38001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /goecho
            pathType: Prefix
            backend:
              service:
                name: go-echo-service
                port:
                  number: 80
